name: Render Quarto Document to GitHub Pages

on:
  pull_request:
    branches: [main, test-gh-pages-ci] # include test branch if you want to test

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.5.2"

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/*.R') }}

      - name: Install R packages
        run: |
          Rscript -e "install.packages(c('tidymodels','tidyverse','janitor','here', 'reticulate'), repos='https://cloud.r-project.org/')"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.1"

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install Python packages
        run: pip install -r requirements.txt

      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Render QMD
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          quarto render mental_health_music/mh_survey_exploration.qmd

      - name: Deploy to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          # Fetch gh-pages or create if missing
          git fetch origin gh-pages
          git checkout gh-pages || git checkout --orphan gh-pages

          # Copy only the new HTML
          cp -r mental_health_music/*.html .

          # Commit and push changes
          git add mental_health_music/*.html
          git commit -m "Update mh_survey_exploration.html" || echo "No changes to commit"
          git push origin gh-pages
